# Generated by Django 3.2.25 on 2025-03-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCheckinRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('total_checkins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckinPerHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('checkin_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckinPerYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('checkin_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CityCheckinRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('total_checkins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommonWithRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avg_stars', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EliteUserPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('ratio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FanMost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('fans', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MostCommonShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shop_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MostStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('five_stars_counts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NewUserEveryYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('user_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('review_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewCountYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewInYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('review_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopMostCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('shop_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopMostState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('shop_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StarsHighCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('average_stars', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalAndSilent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_users', models.IntegerField()),
                ('reviewed_users', models.IntegerField()),
                ('silent_users', models.IntegerField()),
                ('silent_ratio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserEveryYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_user', models.IntegerField()),
            ],
        ),
    ]
