# Generated by Django 3.2.15 on 2025-03-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCheckinRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('total_checkins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckinPerHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('checkin_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckinPerYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('checkin_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CityCheckinRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('total_checkins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommonWithRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avg_stars', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EliteUserPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('ratio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MostCommonShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shop_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MostStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=255)),
                ('five_stars_counts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewInYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('review_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopMostCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('shop_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopMostState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('shop_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StarsHighCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('average_stars', models.FloatField()),
            ],
        ),
    ]
