# Generated by Django 3.2.15 on 2025-03-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark_app', '0003_auto_20250310_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='top5businesses',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
