# Generated by Django 3.2.15 on 2025-03-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark_app', '0005_graphedge_graphnode_topword_userreviewcount_yearreviewcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='cool', max_length=255)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
