# Generated by Django 3.2.25 on 2025-03-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark_app', '0006_wordfrequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmericanReviewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('review_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AmericanReviewStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stars', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ChineseReviewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('review_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChineseReviewStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stars', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MexicanReviewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('review_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MexicanReviewStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stars', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
