# Generated by Django 3.2.15 on 2025-03-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark_app', '0006_wordfrequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('new_users', models.IntegerField()),
                ('review_count', models.IntegerField()),
                ('elite_users', models.IntegerField()),
                ('tip_count', models.IntegerField()),
                ('checkin_count', models.IntegerField()),
            ],
        ),
    ]
