# Generated by Django 3.2.25 on 2025-03-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark_app', '0008_auto_20250311_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantReviewStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_type', models.CharField(max_length=255)),
                ('rating_group', models.CharField(max_length=10)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
