# Generated by Django 3.2.25 on 2025-03-12 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spark_app', '0007_yearlystatistics'),
        ('spark_app', '0009_restaurantreviewstars'),
    ]

    operations = [
    ]
