# Generated by Django 3.2.15 on 2025-03-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark_app', '0011_topcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('stars', models.FloatField()),
                ('total_checkins', models.IntegerField()),
                ('review_count', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
