# Generated by Django 3.2.15 on 2025-03-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark_app', '0012_businessranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(max_length=50)),
                ('word', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
