# Generated by Django 3.2.15 on 2025-03-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(default='', max_length=255, verbose_name='username')),
                ('password', models.CharField(default='', max_length=255, verbose_name='username')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
